const CODE = {
    FLAG_YES        : 'Y',
    FLAG_NO         : 'N',

    APT_TYPE_BOARD       : 'aptTypeBoard',
    APT_TYPE_MAP        : 'aptTypeMap',

    AREA_SEOUL          : 'SEOUL',
    AREA_GANGWON        : 'GANGWON',
    AREA_CHUNGCHEONG    : 'CHUNGCHENOG',
    AREA_GYEONGSANG     : 'GYEONGSANG',
    AREA_JEOLLA         : 'JEOLLA',
    AREA_JEJU           : 'JEJU',

    SIZE_OPTION_FIRST   : 'under-240',
    SIZE_OPTION_SECOND  : 'under-1200',
    SIZE_OPTION_THIRD   : 'under-2400' ,
    SIZE_OPTION_FOURTH  : 'under-12000',
    SIZE_OPTION_FIFTH   : 'up-12000',

    SERVICE_OPTION_SALE : 'SERVICE_SALE',
    SERVICE_OPTION_ADVERTISE : 'SERVICE_ADVERTISE',
    SERVICE_OPTION_CONSULTING : 'SERVICE_CONSULTING',
    SERVICE_OPTION_ALLIANCE : 'SERVICE_ALLIANCE',
    SERVICE_OPTION_ETC : 'SERVCIE_ETC'
}
export default CODE;